### PR TITLE
Fix issue 1205

### LINKED ISSUE #1205: model find  one  and add、update  problem
now , model  find one got a pointer ,  but add、update  is  not a pointer  , expected  same;
@anqiansong

### PR DESCRIPTION
**Pull request by anqiansong**
* fix #1205 
* move builder into stores

### CODE REVIEW

File: core/stores/builderx/builder.go [hunk 1]
```diff
@@ -0,0 +1,91 @@
+package builderx
```
Comment (kevwan) [inline core/stores/builderx/builder.go]: builder? not builderx?

**Review by kevwan — APPROVED** [review]
lgtm
