### PR TITLE
fix import error if generate multiple proto

### LINKED ISSUE #3692: import error if generate multiple proto
**Describe the bug**
当同时生成多个 proto 时，会有 import package 错误的问题，并且与执行的顺序有关

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is
 - 第一次，先生成 protos/a/v1/a.proto，再生成 protos/b/v1/b.proto
   操作:
    image
   import 错误:
    image

- 第二次，先生成 protos/b/v1/b.proto，再生成 protos/a/v1/a.proto
   操作:
    image
    
   import 正确:
    image

2. The error is

**Expected behavior**
无论生成 proto 的顺序如何，import package 都应该是正确的

**Screenshots**
参见上面的图片

**Environments (please complete the following information):**
 - OS: [e.g. macOS]
 - go-zero version [e.g. 1.6.0]
 - goctl version [e.g. 1.6.0]

### PR DESCRIPTION
**Pull request by zzhaolei**
Close #3692.

### CODE REVIEW

File: tools/goctl/rpc/generator/genpb.go [hunk 1]
```diff
@@ -62,7 +62,11 @@ const (
 	grpcSuffix = "_grpc.pb.go"
 )
 
-func findPbFile(current string, grpc bool) (string, error) {
+func findPbFile(current string, src string, grpc bool) (string, error) {
+	protoName := strings.Split(filepath.Base(src), ".")[0]
```
Comment (kesonan) [inline tools/goctl/rpc/generator/genpb.go:66]: It would be more elegant to use the following code：
```go
protoName := strings.TrimSuffix(filepath.Base(src), filepath.Ext(src))
```

**Review by kesonan — APPROVED** [review]
LGTM
