### PR TITLE
fix(goctl): Fix #2561

### LINKED ISSUE #2561: goctl rpc generator produce deprecation message
**Describe the bug**

When I used `goctl rpc template -o transform.proto` it printed `deprecated: goctl rpc template -o is deprecated and will be removed in the future, use goctl rpc -o instead`, but after I switched to use `goctl rpc -o transform.proto`, it produced the same message.

**To Reproduce**

Follow the [shorturl example](https://github.com/zeromicro/zero-doc/blob/main/doc/shorturl.md).

**Expected behavior**

Don't show the deprecation message when use the new rpc command.

**Screenshots**

image

**Environments (please complete the following information):**
 - OS: Linux
 - go-zero version v1.4.2
 - goctl version 1.4.2

**More description**

### PR DESCRIPTION
**Pull request by anqiansong**

### CODE REVIEW

File: tools/goctl/rpc/cli/cli.go [hunk 1]
```diff
@@ -104,8 +105,10 @@ func RPCNew(_ *cobra.Command, args []string) error {
 }
 
 // RPCTemplate is the entry for generate rpc template
-func RPCTemplate(_ *cobra.Command, _ []string) error {
-	console.Warning("deprecated: goctl rpc template -o is deprecated and will be removed in the future, use goctl rpc -o instead")
+func RPCTemplate(new bool) error {
+	if !new {
```
Comment (kevwan) [inline tools/goctl/rpc/cli/cli.go:109]: don't use keyword `new`.

File: tools/goctl/rpc/cmd.go [hunk 2]
```diff
@@ -2,6 +2,7 @@ package rpc
 
 import (
 	"github.com/spf13/cobra"
+
```
Comment (kevwan) [inline tools/goctl/rpc/cmd.go:5]: remove blank lines for consistency.

File: tools/goctl/rpc/cli/cli.go [hunk 3]
```diff
@@ -7,6 +7,7 @@ import (
 	"strings"
 
 	"github.com/spf13/cobra"
+
```
Comment (kevwan) [inline tools/goctl/rpc/cli/cli.go:10]: remove blank lines for consistency.
