### PR TITLE
fix(goctl): api format with reader input

### LINKED ISSUE #1721: goctl-vscode Formatting files fails when there is `import` literal
`goctl-vscode` only passes the file data to `goctl`, which is not enough.
I will try to solve this problem.

### PR DESCRIPTION
**Pull request by fynxiu**
resolves #1721
There's also a relative PR https://github.com/zeromicro/goctl-vscode/pull/12

### CODE REVIEW

**Comment by fynxiu** [comment]
BTW, this also fixes https://github.com/zeromicro/goctl-vscode/issues/11

File: tools/goctl/api/format/format.go [hunk 1]
```diff
@@ -29,14 +30,14 @@ const (
 func GoFormatApi(c *cli.Context) error {
 	useStdin := c.Bool("stdin")
 	skipCheckDeclare := c.Bool("declare")
+	dir := c.String("dir")
```
Comment (anqiansong) [inline tools/goctl/api/format/format.go:33]: 这里应该在cli中声明一下flag？
--
Should the flag be declared in the cli?

Comment (fynxiu) [reply tools/goctl/api/format/format.go:33]: @anqiansong It's already there.
