### PR TITLE
fix: SlowThreshold configuration not taking effect

### LINKED ISSUE #4641: How to set slowThreshold
In the function below, slowThreshold is used to determine if a call is slow. However, when I try to modify slowThreshold using SetSlowThreshold function, the comment suggests using StatConf instead. StatConf.SlowThreshold is passed into the logDuration function as the durationThreshold parameter. It is only used in the **if isSlow(duration, durationThreshold)** check, but it does not affect slowThreshold. Does this indicate a bug?

```go
func logDuration(ctx context.Context, method string, req any, duration time.Duration,ignoreMethods *collection.Set, durationThreshold time.Duration) {

      ...

	if !shouldLogContent(method, ignoreMethods) {
		if isSlow(duration, durationThreshold) {
			logger.Slowf("[RPC] slowcall - %s - %s", addr, method)
		}
	} else {
		content, err := json.Marshal(req)
		if err != nil {
			logx.WithContext(ctx).Errorf("%s - %s", addr, err.Error())
		} else if duration > slowThreshold.Load() {
			logger.Slowf("[RPC] slowcall - %s - %s - %s", addr, method, string(content))
		} else {
			logger.Infof("%s - %s - %s", addr, method, string(content))
		}
	}
}



// SetSlowThreshold sets the slow threshold.
// Deprecated: use StatConf instead.
func SetSlowThreshold(threshold time.Duration) {
	slowThreshold.Set(threshold)
}
```

### PR DESCRIPTION
**Pull request by Nanosk07**
fix #4641

### CODE REVIEW

File: zrpc/internal/serverinterceptors/statinterceptor.go [hunk 1]
```diff
@@ -63,8 +63,7 @@ func UnaryStatInterceptor(metrics *stat.Metrics, conf StatConf) grpc.UnaryServer
 }
 
 func isSlow(duration, durationThreshold time.Duration) bool {
-	return duration > slowThreshold.Load() ||
```
Comment (kevwan) [inline zrpc/internal/serverinterceptors/statinterceptor.go:66]: Why changed the check? I think we also need to consider slowThreshold, because users might set it.

**Review by kevwan — CHANGES_REQUESTED** [review]

**Review by kevwan — APPROVED** [review]

File: zrpc/internal/serverinterceptors/statinterceptor.go (hunk 1 above)
Comment (Nanosk07) [reply zrpc/internal/serverinterceptors/statinterceptor.go:66]: **slowThreshold** has a default value, and if the duration exceeds 500ms, the function will return duration > slowThreshold.Load() directly. The durationThreshold will only take effect when the users configure it to be below 500ms. If want to set a threshold above 500ms, they still need to use the deprecated SetSlowThreshold function. Therefore I modified the check.
```go
func isSlow(duration, durationThreshold time.Duration) bool {
	return duration > slowThreshold.Load() ||
		(durationThreshold > 0 && duration > durationThreshold)
}
```

Comment (Nanosk07) [reply zrpc/internal/serverinterceptors/statinterceptor.go:66]: > Why changed the check? I think we also need to consider slowThreshold, because users might set it.

**slowThreshold** has a default value, and if the duration exceeds 500ms, the function will return duration > slowThreshold.Load() directly. The durationThreshold will only take effect when the users configure it to be below 500ms. If want to set a threshold above 500ms, they still need to use the deprecated SetSlowThreshold function. Therefore I modified the check.
```go
func isSlow(duration, durationThreshold time.Duration) bool {
	return duration > slowThreshold.Load() ||
		(durationThreshold > 0 && duration > durationThreshold)
}
```
