### PR TITLE
Fix #1238

### LINKED ISSUE #1238: Duplicate routing errors occur when using the prefix option in API file groups
**Describe the bug**

**To Reproduce**
`goctl api go -api ./issue.api -dir .`

1. The code is

  issue.api
  ```api
syntax = "v1"

info(
    title: "just demo"
    desc: "type desc here"
    author: "zfkun"
    email: "zfkun@msn.com"
    version: "0.0.1"
)

type (
    UserInitReq {
        Name string `json:"name"`
    }

    UserInitReply {
        Id uint64 `json:"id"`
    }

    UserLoginReq {
        Name string `json:"name"`
    }

    UserLoginReply {
        Success bool `json:"success"`
    }

    AdminInitReq {
        Name string `json:"name"`
    }

    AdminInitReply {
        Id uint64 `json:"id"`
    }

    AdminLoginReq {
        Name string `json:"name"`
    }

    AdminLoginReply {
        Success bool `json:"success"`
    }
)


@server(
    group: user
    prefix: /user
)
service issue-api {
    @doc "init for user service"
    @handler init
    post /init (UserInitReq) returns (UserInitReply)

    @doc "login for user service"
    @handler login
    post /login (UserInitReq) returns (UserInitReply)
}


@server(
    group: admin
    prefix: /admin
)
service issue-api {
    @doc "init for user service"
    @handler init
    post /init (AdminInitReq) returns (AdminInitReply)

    @doc "login for user service"
    @handler login
    post /login (AdminLoginReq) returns (AdminLoginReply)
}
  ```

2. The error is

  ```
./issue.api line 68:4  duplicate route 'post /init'
goctl: generation error: ./issue.api line 68:4  duplicate route 'post /init'
goctl version: 1.2.3 darwin/amd64
   ```

**Expected behavior**
I think, route's key for filter should include the value of `prefix`.
Thanks.

**Screenshots**
none

**Environments (please complete the following information):**
 - OS: MacOS
 - go-zero version 1.2.3
 - goctl version 1.2.3

**More description**
none

### PR DESCRIPTION
**Pull request by anqiansong**

### CODE REVIEW

File: tools/goctl/api/parser/g4/ast/api.go [hunk 1]
```diff
@@ -49,8 +50,15 @@ func (v *ApiVisitor) acceptService(root, final *Api) {
 		}
 		v.duplicateServerItemCheck(service)
 
+		var prefix string
+		if service.AtServer != nil {
+			p := service.AtServer.Kv.Get("prefix")
```
Comment (kevwan) [inline tools/goctl/api/parser/g4/ast/api.go:55]: use constant to define `prefix`, used more than once.

File: tools/goctl/api/parser/g4/ast/apiparser.go [hunk 2]
```diff
@@ -239,6 +240,13 @@ func (p *Parser) valid(mainApi, nestedApi *Api) error {
 
 func (p *Parser) duplicateRouteCheck(nestedApi *Api, mainHandlerMap, mainRouteMap map[string]PlaceHolder) error {
 	for _, each := range nestedApi.Service {
+		var prefix string
+		if each.AtServer!=nil {
```
Comment (kevwan) [inline tools/goctl/api/parser/g4/ast/apiparser.go:244]: format the code, otherwise ci will fail.

File: readme-cn.md [hunk 3]
```diff
@@ -104,10 +104,10 @@ GO111MODULE=on GOPROXY=https://goproxy.cn/,direct go get -u github.com/tal-tech/
 
     ```shell
     # Go 1.15 及之前版本
-    GO111MODULE=on GOPROXY=https://goproxy.cn/,direct go get -u github.com/tal-tech/go-zero/tools/goctl
+    GO111MODULE=on GOPROXY=https://goproxy.cn/,direct go get -u github.com/tal-tech/go-zero/tools/goctl@cli
     
     # Go 1.16 及以后版本
-    go install github.com/tal-tech/go-zero/tools/goctl@latest
+    GOPROXY=https://goproxy.cn/,direct go install github.com/tal-tech/go-zero/tools/goctl@cli
```
Comment (kevwan) [inline readme-cn.md:110]: reset your master branch before checkout new branch.

this is the changes from previous merged commits.

File: tools/goctl/api/parser/g4/ast/apiparser.go [hunk 4]
```diff
@@ -3,6 +3,7 @@ package ast
 import (
 	"fmt"
 	"io/ioutil"
+	path2 "path"
```
Comment (kevwan) [inline tools/goctl/api/parser/g4/ast/apiparser.go:6]: only one path in imports, change the `path` variable to other names. and keep import as path.

**Review by kevwan — CHANGES_REQUESTED** [review]

File: readme-cn.md (hunk 3 above)
Comment (anqiansong) [reply readme-cn.md:110]: It already rebase on master

**Review by kevwan — APPROVED** [review]
lgtm
